### ISSUE TITLE
pxer新状况-。-

### ISSUE THREAD

**Issue by krnagi** [pea3nut/Pxer#10]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Firefox ESR 52.0.1 (32 位)
- Pxer开发版

## Bug发生时的地址
每个-。-

## Bug发生时Pxer的状态
pxer的界面没有出来

## Bug发生的具体情况
pxer的界面没有出来，但是标签页的logo是出来了

**Comment by krnagi** [comment]
那个……我让两个朋友试了也是这样-。-

**Comment by pea3nut** [comment]
这次用Git部署的，忘了加个文件，现在好了
