### ISSUE TITLE
Pxer日志收集

### ISSUE THREAD

**Issue by pea3nut** [pea3nut/Pxer#104]
## 当前Pxer功能的局限

无法看到Pxer的用户画像，对于Pxer用户的一切数据，我们都不知道

## 你期望增加/修改的功能

在 `build/server.js` 中加入日志功能，记录：

- --用户是谁（用户ID）--已删除。这样数据就是匿名的了
- 用户在什么时间启动了Pxer
- 用户使用了Pxer哪个功能
- referer（似乎略敏感？不过数据完全都是匿名的了应该无所谓？）

**Comment by eternal-flame-AD** [comment]
直接控制台输出还是用什么其他上游服务？

**Comment by pea3nut** [comment]
@eternal-flame-AD 我没有想好特别明确的技术方案，但是尽可能的希望让Pxer减少依赖。或许文件数据库是个不错的主意。数据可视化放在另一次做

**Comment by NSDie** [comment]
时间跟功能还好说  用户ID是登录的那个吗

**Comment by NSDie** [comment]
那如果搭一个服务器 然后 使用的时候他们会post数据到后台

**Comment by pea3nut** [comment]
好像用户ID挺难拿到了，而且有点敏感（？），干脆不要，这样数据完全是匿名的，拿referer怎么样？

**Comment by eternal-flame-AD** [comment]
referer好像没有什么对项目的实际价值？

更有价值的应该是有哪些不被支持的页面真正有需求？

**Comment by pea3nut** [comment]
@eternal-flame-AD 任何数据都是有价值的。

比如，若referer发现用户在某些页面请求频率非常高，且页面内容相对固定。是不是可以让服务器缓存抓取结果，实现0秒抓取10000张的效果呢？

比如，发现大量用户都使用 `000user` 这个tag，且持续使用数月不充P站会员，是不是Pxer可以提供按需付费的P站会员热门排序呢？P站、用户、Pxer实现三赢局面

或许有更有趣的分析结果，可以带来更有价值的功能。

**Comment by pea3nut** [comment]
经过慎重考虑，我建议收集以下数据：

- 用户在什么时间启动了Pxer
- 用户使用了Pxer哪个功能

以下数据不会被收集：

- referer
- 用户ID
- 用户使用Pxer报错后的报错信息

@eternal-flame-AD 将 #105 调整下裁决策略吧。
