### ISSUE TITLE
询问关于官方QQ群

### ISSUE THREAD

**Issue by bravadoops** [pea3nut/Pxer#109]
JS初学者，想学习客户端爬虫找到了这个项目。
想加QQ群交流一下，但是官网上的链接点击无法跳转（macOS） 公告里留的群号似乎是给开发者用的（790688748）目前是初学者，不知道有没有专门用于问问题和讨论的群？谢谢

**Comment by eternal-flame-AD** [comment]
还有个这个群37369013，这个是用户交流群，不聊开发的
开发者群也可以进去看看的呐QWQ

**Comment by pea3nut** [comment]
Pxer官网[大部分页面](http://pxer.pea3nut.org/md/start)底部都有一个 *其他相关链接* ，第一条就是官方QQ群。
