### ISSUE TITLE
显示此网页时内存不足

### ISSUE THREAD

**Issue by s01o** [pea3nut/Pxer#11]
## 使用的系统、浏览器、Pxer版本

- Windows 7
- CHROME 火狐 水狐 猎豹 QQ  全试了
- 两个都试了

## Bug发生时的地址

http://www.pixiv.net/search.php?s_mode=s_tag&word=leagueoflegends

## Bug发生时Pxer的状态

抓取状态中，大概抓到8000多张临近任务结束的时候，整个页面卡住不动，过个十几秒钟网页变白显示
google chrome 在尝试显示此网页时内存不足

## Bug发生的具体情况

当我用Pxer抓取上面地址的作品时，抓取到后面的时候会卡住不动

**Comment by pea3nut** [comment]
内存占用问题计划会在7.1.x版本修复，需要改动逻辑部分

或者可以加一个“跳过前x副作品”的功能，这样可以分段下载

**Comment by pea3nut** [comment]
仔细一想，貌似这种反而是对P站的一种保护，所以不修了~~
