### ISSUE TITLE
关于Safari用户安装Tampermonkey的安装教程

### ISSUE THREAD

**Issue by simon300000** [pea3nut/Pxer#12]
使用Safari的用户不能在官方插件网站搜索到，需要到[http://tampermonkey.net](http://tampermonkey.net)下载
把网站给标注上会不会是一个好办法？

**Comment by pea3nut** [comment]
欸我都忘了这款浏览器了......

也对，既然是js脚本，理论上Mac/Linux也能跑。

**Comment by simon300000** [comment]
就我这里测试Safari是能跑的→_→

**Comment by pea3nut** [comment]
好了，在首页无耻的加上了“支持Windows/Mac/Linux系统”，并且在[安装页面_1](http://pxer.pea3nut.org/md/install_1)增加了Safari浏览器的相关说明
