### ISSUE TITLE
Pixiv无法打开

### ISSUE THREAD

**Issue by SeekingMini** [pea3nut/Pxer#127]
求助！已经修改过hosts文件了，还是无法打开P站！有没有解决方法呢？

**Comment by eternal-flame-AD** [comment]
I think this is unrelated to this project. Closing. Feel free to join the group for discussion or email me.

Here I will give some options that could work:

1. Use a proxy or VPN to bypass the firewall (recommended and easiest)

2. Write an HTTPS Man-in-the-Middle to strip off the SNI extension from the TLS handshake from the browser. I hadn't found an implementation on Github yet. Maybe you need to write your own.

3. Use a browser that does not support TLS SNI extension. (The version would be really old and is not guaranteed to work) https://caniuse.com/#feat=sni

**Comment by eternal-flame-AD** [comment]
I think it is also possible to build a browser from source like [chromium](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj935Lekb_dAhXDXSwKHbllCfAQFjAAegQICxAB&url=https%3A%2F%2Fwww.chromium.org%2F&usg=AOvVaw3DJn_ew9xLfgVfpqDKfP66) with modifications on the TLS handshake procedure.

**Comment by eternal-flame-AD** [comment]
这个和项目开发无关，就不在这里追踪了，可以加群讨论或者和我email

给几个可能的思路：

- 科学×× 最简单也最有效
- 写一个HTTPS中间人，去除或伪造TLS握手中的SNI，没看到现成的方案你可能得自己写
- 用不支持SNI扩展的浏览器，版本实在实在很老，我开玩笑的
- 修改开源的浏览器如chromium在tls握手部分的源代码，去除sni然后重新编译
