### ISSUE TITLE
CGI抓取时ID过滤不正确

### ISSUE THREAD

**Issue by sivor0811** [pea3nut/Pxer#133]
## 当前Pxer功能的局限
目前只能抓取ID為設定之前的
例如作者更新了圖片ID為300
但是只能設定之前的
所以抓不到作者新的圖片

## 你期望增加/修改的功能

希望可以新增抓取ID為設定之後的
例如要抓作者新上傳的ID為300和400
則只要設定300
就會自動抓取出ID300和400的圖
而不會抓取到以前的圖

**Comment by eternal-flame-AD** [comment]
应该是有的，现在有一个抓到指定ID停止的功能

**Comment by sivor0811** [comment]
我使用後發現如上面所說的
只能抓到之前的抓不到之後的
pixiv ID是遞增的方式創造
所以只能抓到舊圖

**Comment by eternal-flame-AD** [comment]
感谢，是一个bug

cgi返回顺序是ID递增，和之前通过view获取的顺序相反所以挂了
