### ISSUE TITLE
抓去图片时显示一段代码

### ISSUE THREAD

**Issue by DCTYG** [pea3nut/Pxer#17]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Google Chrome 56.0.2924.87 (64-bit)
- Pxer开发版

## Bug发生时的地址

http://www.pixiv.net/member_illust.php?id=3875056

## Bug发生时Pxer的状态

主面板提示：
[ { "task": { "url": [ "http://www.pixiv.net/member_illust.php?mode=medium&illust_id=57114488" ], "html": {}, "completed": false, "type": "illust", "isMultiple": false, "id": "57114488" }, "url": "http://www.pixiv.net/member_illust.php?mode=medium&illust_id=57114488" } ]

## Bug发生的具体情况

开始抓取图片时显示以上代码。

**Comment by pea3nut** [comment]
是开始抓取图片的时候就显示？Pxer的当前进度显示什么？

**Comment by pea3nut** [comment]
应该是P站部分更换HTTPS的问题吧，现在在7.0.4中更换了HTTPS应该没问题了吧？

有问题再开issue就好了，先close了
