### ISSUE TITLE
点击run后提示 46920843:Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by gareiz** [pea3nut/Pxer#18]
## 使用的系统、浏览器、Pxer版本

- Windows 10 RS1
- Chrome 57.0.2987.133  32bit
- Pxer开发版

## Bug发生时的地址

http://www.pixiv.net/member_illust.php?id=2894963  （R18注意）

## Bug发生时Pxer的状态

点击run后提示 46920843:Cannot read property 'innerHTML' of null

## Bug发生的具体情况

点击run后提示 46920843:Cannot read property 'innerHTML' of null
重试几次之后一样如此
失败原因显示解析错误

**Comment by gareiz** [comment]
发现http://www.pixiv.net/member_illust.php?id=15657814
这个画师的也不行，显示
60366904:Cannot read property 'innerHTML' of null

**Comment by SetoKaiba** [comment]
https://rawgit.com/SetoKaiba/Pxer/dev/pxer-dev.user.js
可以临时先用一下这个，因为P站的评分系统改了。。从以前10分满分改成现在直接点赞，所以没有了总分。。导致这个报错。。
作者据说在360很忙，剩下的等他回归后修正后再看怎么办吧。。我的修正是直接把所有赞都当成满分10分。。
