### ISSUE TITLE
P站换成HTTPs后Pxer无法启动

### ISSUE THREAD

**Issue by pea3nut** [pea3nut/Pxer#20]
由于P站改动换成了HTTPs，由于一些HTTPs限制，Pxer暂时无法启动，请等待后续版本修复。

我们将持续用此issue追踪此问题

**Comment by pea3nut** [comment]
之前没接触过HTTPs，可能需要修复一段时间，修复好了需要手动升级，到时候会提示

**Comment by SetoKaiba** [comment]
https://rawgit.com/SetoKaiba/Pxer/dev/pxer-dev.user.js
临时修正版，之后就是坐等作者修正了。。
还是和之前一样，作者更新了能用的我就删掉fork。。

**Comment by pea3nut** [comment]
已修复，需重新安装Pxer，详细见：
https://github.com/pea3nut/Pxer/releases/tag/7.0.4
