### ISSUE TITLE
抓不了动图了

### ISSUE THREAD

**Issue by SetoKaiba** [pea3nut/Pxer#22]
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=62536800

下面这段代码，isMultiple是false了，所以抓不了动图了。
https://github.com/pea3nut/Pxer/blob/dev/src/app/class/PxerApp.3.class.js#L259-L277

**Comment by pea3nut** [comment]
动图本身没有打包属于“半残废”阶段，容我拖一拖攒一攒再修复吧。。。

**Comment by eternal-flame-AD** [comment]
目前抓取正常，medium界面无法抓取动图的问题，track it in #70

**Comment by eternal-flame-AD** [comment]
问题定义已经有变化。在 #70 跟踪这个问题
