### ISSUE TITLE
UC浏览器，WIN10系统，油猴子还有PXER均已安装，无报错，但是无法启用软件

### ISSUE THREAD

**Issue by machao1283** [pea3nut/Pxer#28]
## 使用的系统、浏览器、Pxer版本

- Windows 7
- Firefox 延长支持版 47.4.0
- Pxer开发版 6.0.2

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?id=10009740

## Bug发生时Pxer的状态

“程序状态”窗口的“当前状态”一直卡在“抓取作品中”不动，并且主面板有提示`src.match(...) is null`。

## Bug发生的具体情况

当我用Pxer抓取上面地址的画师作品时，抓取到后面的时候偶尔会（30%几率左右的样子）在差10副作品左右时卡住不动，尝试过点击`Stop`按钮依旧无效。

**Comment by pea3nut** [comment]
我给出的模板的意思是：根据模板填写真实信息。结果你只改了标题，模板原封不动给提交上来了。。。

不过估计这个bug和之前有人提交的差不多，应该是回调层级太多。所以暂时先close了，等解决那个bug，如果此问题依旧，那么再开也不迟
