### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by unintialized** [pea3nut/Pxer#31]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- chrome 60.0.3112.101（正式版本） （64 位）
- Pxer开发版 7

## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=saber%20%2010000users%E5%85%A5%E3%82%8A

## Bug发生时Pxer的状态
停止工作,剩余时间不断增加

主面板有提示"PxerApp.executeWroksTask: taskList is empty"

## Bug发生的具体情况

当我用Pxer抓取上面地址的搜索作品时，抓取到后面的时候就会出现上述情况.

**Comment by pea3nut** [comment]
see https://github.com/pea3nut/Pxer/issues/38
