### ISSUE TITLE
无法抓取的bug

### ISSUE THREAD

**Issue by GOLDENLULUZ** [pea3nut/Pxer#32]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- chrome 61.0.3163.79
- Pxer开发版与稳定版，两个最新版

## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E3%83%9D%E3%82%B1%E3%83%A2%E3%83%B3
实际上是所有网址

## Bug发生时Pxer的状态

PxerApp.executeWroksTask: taskList is empty

## Bug发生的具体情况

当我试图抓取时，pxer会在一个特定的图的位置弹出上述提示并卡住，点击stop后不会出现前几副图的下载按钮。
例如，我选择抓取前1000副，会显示任务数1050，然后卡在第50副。或者2000，2100，100。以此类推。

**Comment by pea3nut** [comment]
手里积压了2个项目，好愁人！！！！

我个人主观想要修复Pxer，但是客观要求我开发另一个项目。。。

天啦撸，每天还有工作要做

**Comment by pea3nut** [comment]
要是哪天，这个项目突然没人维护了，QQ群里的花生的QQ也离线了。

不用怀疑，花生从来不隐身，一定是猝死了

**Comment by Tyrone1875** [comment]
我这里也是这个问题，而且卡住的比例永远是在4.747%

**Comment by Fireflaker** [comment]
同样的问题

**Comment by zgbjwzh** [comment]
同样的问题

**Comment by pea3nut** [comment]
贴的P站地址有几十万副作品，实在没办法测试。版本7.0.6应该修好了。如果问题依旧在开issue就好。贴P站地址尽量贴一个作品数少一点的。
