### ISSUE TITLE
抓取失败的bug

### ISSUE THREAD

**Issue by bxystardust** [pea3nut/Pxer#33]
使用的系统、浏览器、Pxer版本

- Windows 10
- 360极速浏览器
- Pxer开发版和稳定版最新版本

Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E8%89%A6%E3%81%93%E3%82%8C%2010000users%E5%85%A5%E3%82%8A

Bug发生时Pxer的状态

PxerApp.executeWroksTask: taskList is empty
 Stop

Bug发生的具体情况

当我用Pxer抓取上面地址的作品时，抓取到某一特定图片时就会停止。点击stop就只显示：PxerApp.executeWroksTask: taskList is empty，重新抓取还是停在同一位置。

**Comment by pea3nut** [comment]
你给出的地址内容多的太夸张了，一共525653件，我没办法测试。

一方面，Pxer抓太多的图片数会因为内存不够而奔溃，Pxer本身就不是设计来抓取数万作品的。另一方面，这样会对P站造成一定压力，而你要那么多图片也筛选不过来

**Comment by pea3nut** [comment]
关掉这个bug了，追踪进度放在 #32
