### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by zgbjwzh** [pea3nut/Pxer#38]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Google Chrome 64.0.3282.186（正式版）（64位）
- Pxer7
## Bug发生时的地址

在下载搜索页面时
在下载个人页面时可以下载，但是搜索页面时报错

## Bug发生时Pxer的状态

“程序状态”窗口的“当前状态”一直卡在“抓取作品中”不动，时间还在动，并且主面板有提示`PxerApp.executeWroksTask: taskList is empty
`。

## Bug发生的具体情况

当我用Pxer抓取搜索的作品时，会在大约抓到百分之十的时候开始报错，尝试过点击`Stop`按钮依旧无效。每次都是这样。

**Comment by pea3nut** [comment]
测试了如下地址，已经可以正常工作：
- https://www.pixiv.net/search.php?s_mode=s_tag&word=saber%20%2010000users%E5%85%A5%E3%82%8A
- https://www.pixiv.net/search.php?s_mode=s_tag&word=VOCALOID+50000user
