### ISSUE TITLE
搜索页Pxer只能重复抓取当前页的图片

### ISSUE THREAD

**Issue by silevilence** [pea3nut/Pxer#39]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Chrome 64.0.3282.186（正式版本）（64 位）
- Pxer开发版 7.0.6

## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E3%83%89%E3%83%A9%E3%81%88%E3%82%82%E3%82%93%20000user

试了几个搜索页都有这个问题，上面的地址是Readme里面提到的搜索页

## Bug发生时Pxer的状态

正常结束运行

## Bug发生的具体情况

使用Pxer抓取搜索页时，虽然能够正常结束，但是当使用idm下载时发现去除了巨量的重复文件。

将url列表粘贴到vim里面sort一下，发现url重复了大概页码的次数（以上面的链接来说是7次）。进行去重复的操作后，发现剩余30多项，大概和一页的图片数量差不多。

下载去重后的列表，发现都是第一页的图片（顺便404的好像有点多）。

[pics.txt](https://github.com/pea3nut/Pxer/files/1773916/pics.txt)
↑排序后的文件

把搜索结果切到第二页试了一下，结果差不多，但是抓到的都是第二页的图片……

在画师作品页上没有这个问题（没有重复的链接），稳定版在搜索页上也有这个问题。

**Comment by pea3nut** [comment]
简单来说，现在Pxer还是能完成正常工作，只是有许多多余动作。是这样吗？

**Comment by silevilence** [comment]
只有一页的话是正常的，但是有多页的话就只能重复获得当前页的图片了。

**Comment by pea3nut** [comment]
P站开始用 React 重写了，因为搜索页被重写完成了，因此Pxer挂了。这次加了个 Hook，自动检测是否被 React 重写，然后使用新的抓取方法。
