### ISSUE TITLE
38363308:Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by mikuo-akita** [pea3nut/Pxer#41]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- chrome浏览器，版本（稳定版）64.0.3282.186
- Pxer开发版 7.0.8

## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E9%8F%A1%E9%9F%B3%E3%83%AA%E3%83%B3&order=popular_d

## Bug发生时Pxer的状态

抓取完成后，主程序顶部显示“38363308:Cannot read property 'getAttribute' of null
”的错误

## Bug发生的具体情况

抓取完成后，总会有少数一些图片解析错误，重试仍然不行；画师的作品列表不会有这个bug。
![qq 20180307152042](https://user-images.githubusercontent.com/36428746/37078705-49b45d96-221b-11e8-9837-8b849f52e662.png)

**Comment by eternal-flame-AD** [comment]
7.0.10版本已正常
