### ISSUE TITLE
Pxer抓取部分图片解析错误

### ISSUE THREAD

**Issue by jiaer24** [pea3nut/Pxer#44]
## 使用的系统、浏览器、Pxer版本

- Windows 10教育版
- Google Chrome 版本 64.0.3282.186（正式版本） （32 位）
- Pxer7
## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E4%BA%94%E6%9B%B4%E7%91%A0%E7%92%83%20500users%E5%85%A5%E3%82%8A

## Bug发生时Pxer的状态

抓取完成显示警告

34942856:Cannot read property 'getAttribute' of null   
62496903 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
62326688 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
62195545 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
57524390 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
56436071 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
51872918 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
35291218 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
34942856 | 解析错误 | 再试一次，若问题依旧，请反馈给花生

## Bug发生的具体情况

当我用Pxer抓取上面地址的作品时，抓取完成会出现若干错误，未错误的作品能正常解析地址。

**Comment by eternal-flame-AD** [comment]
新版本已修复
