### ISSUE TITLE
Pxer抓取多张图片错误或只能抓取第一张图

### ISSUE THREAD

**Issue by MARKGREEN1232** [pea3nut/Pxer#45]
https://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E8%A6%8B%E5%B4%8E%E9%B3%B4&order=popular_d&blt=1000

其中很多张图片抓取后只有第一张图（_0），抓取不到除了第一张之外的其他图片。
这个页面抓取的结果
https://i.pximg.net/img-original/img/2017/07/04/03/38/42/63696387_p0.jpg
https://i.pximg.net/img-original/img/2012/03/14/05/41/51/25783560_p0.jpg
https://i.pximg.net/img-original/img/2017/01/29/10/04/18/61168443_p0.jpg
https://i.pximg.net/img-original/img/2012/03/03/01/15/12/25498688_p0.jpg
https://i.pximg.net/img-original/img/2012/02/19/00/07/07/25186134_p0.jpg
https://i.pximg.net/img-original/img/2012/03/26/11/31/19/26091584_p0.jpg
https://i.pximg.net/img-original/img/2017/12/21/16/44/17/66379223_p0.jpg
https://i.pximg.net/img-original/img/2012/04/05/23/11/20/26366274_p0.png
https://i.pximg.net/img-original/img/2012/03/13/00/31/42/25755382_p0.jpg
https://i.pximg.net/img-original/img/2012/03/10/00/20/58/25674431_p0.jpg
https://i.pximg.net/img-original/img/2012/02/16/01/32/18/25120832_p0.jpg
https://i.pximg.net/img-original/img/2012/03/23/02/04/56/26007756_p0.png
https://i.pximg.net/img-original/img/2012/01/22/16/51/05/24538113_p0.jpg
https://i.pximg.net/img-original/img/2012/03/27/09/46/55/26115380_p0.jpg
https://i.pximg.net/img-original/img/2012/01/20/05/04/11/24484541_p0.png
https://i.pximg.net/img-original/img/2012/05/30/23/31/59/27614027_p0.png
https://i.pximg.net/img-original/img/2012/02/15/00/59/47/25096164_p0.jpg
https://i.pximg.net/img-original/img/2013/02/06/07/49/46/33366678_p0.jpg
https://i.pximg.net/img-original/img/2012/02/21/00/35/16/25237616_p0.jpg
https://i.pximg.net/img-original/img/2012/02/16/12/43/18/25126506_p0.jpg
https://i.pximg.net/img-original/img/2012/02/19/12/08/21/25196040_p0.png
https://i.pximg.net/img-original/img/2012/08/12/09/59/21/29316620_p0.jpg
https://i.pximg.net/img-original/img/2012/03/18/02/50/36/25883065_p0.jpg

除去一个抓取失败的，其他的有四张图是组图，却只抓取到了第一张

**Comment by eternal-flame-AD** [comment]
这个现在会有一个task illegal，正在调查

**Comment by eternal-flame-AD** [comment]
7.0.10版本已正常
