### ISSUE TITLE
抓取失败

### ISSUE THREAD

**Issue by mouyuu** [pea3nut/Pxer#46]
抓取页报告
错误报告：http:600
/** 这个页面是抓取到的下载地址，你可以将它们复制到第三方下载工具如QQ旋风中下载 */
/**
共计0个作品，0个下载地址。
单张图片作品占 NaN%
多张图片作品占 NaN%
*/

## 使用的系统、浏览器、Pxer版本

- Windows 7
- chrome  65.0.3325.181
- Pxer开发版 7

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=67946094等（一个时间段之后的所有链接）

## Bug发生的具体情况

抓取一定数量后发生此情况，是不是因为IP的流量限制_(:з」∠)_

**Comment by pea3nut** [comment]
应该就是正常P站改动导致的Pxer程序bug 。。。

**Comment by eternal-flame-AD** [comment]
新版本测试正常

**Comment by pea3nut** [comment]
@eternal-flame-AD 最好说清是哪一个“新版本”，因为“新版本 ”总有一天会变成“旧版本”
