### ISSUE TITLE
pxer.pea3nut.org的https证书不正确

### ISSUE THREAD

**Issue by simon300000** [pea3nut/Pxer#47]
偶然发现的，是pxer-app.pea3nut.org的

**Comment by pea3nut** [comment]
赛门的证书听说说要全面取缔。。。不过我测试最新版的Chrome和FIreFox暂时是没问题的，你的环境是什么？

**Comment by simon300000** [comment]
似乎不是证书颁发者不受信任，我这里看到是这个网站配置了另外一个网站的证书
默认也不是https，我手动加在地址栏就变成这样了

(Let’s Encrypt大法好

Safari 11.1

截图：
<img width="463" alt="image" src="https://user-images.githubusercontent.com/12656264/38452953-876343dc-3a80-11e8-8d6e-6288007ee3be.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/12656264/38452959-9e17730a-3a80-11e8-87dd-21a97452b162.png">

**Comment by pea3nut** [comment]
![default](https://user-images.githubusercontent.com/13781420/38453162-c9fa4bac-3a83-11e8-94f2-7fc7cf30b442.png)

找时间升级下Mac再测试吧。。。

**Comment by simon300000** [comment]
不对不对，是 https://pxer.pea3nut.org 的证书 不是 https://pxer-app.pea3nut.org

**Comment by pea3nut** [comment]
`pxer.pea3nut.org` 这个网站确实没证书。网站内容没什么数据提交，只是用来放文档，所以就没上 https ，而 `pxer-app.pea3nut.org` 是存放 Pxer 源文件的，因为P站是 https 的，所以载入Pxer源文件也必须是 https。

**Comment by simon300000** [comment]
→_→
