### ISSUE TITLE
解析错误 68301576:dom.querySelector(...) is null

### ISSUE THREAD

**Issue by Bill-Wo** [pea3nut/Pxer#49]
68301576:dom.querySelector(...) is null
![14](https://user-images.githubusercontent.com/38727275/39250624-d1ec27fa-48d3-11e8-8400-2dbb16d25dfb.png)

## 使用的系统、浏览器、Pxer版本
- Windows 10 专业版 1803
- Firefox 59.0.3 (64 位)
- Pxer 7.0.8 稳定版

## Bug发生时的地址
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68301576

## Bug发生的具体情况
解析地址的时候出现错误。网络状况良好，使用hosts，Onedrive正在同步上传文件。

**Comment by Bill-Wo** [comment]
更新了系统信息（Windows 10 Pro 1709→1803）、浏览器信息（Firefox 59.0.2→59.0.3），错误仍存在。

**Comment by pea3nut** [comment]
fixed in 7.0.9
