### ISSUE TITLE
68378771:dom.querySelector(...) is null 

### ISSUE THREAD

**Issue by TheRealKamisama** [pea3nut/Pxer#50]
## 使用的系统、浏览器、Pxer版本

- Windows 10 专业版 1709
- Firefox 32bit 59.0.3
- Pxer开发版 7

## Bug发生时的地址
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68378771
别的地址没什么差别，都是相同的问题

## Bug发生时Pxer的状态

抛出一个warning：68378771:dom.querySelector(...) is null 

## Bug发生的具体情况
![qq 20180501233435](https://user-images.githubusercontent.com/35005476/39479744-bb625a58-4d98-11e8-804c-1713dc504fdb.png)

**Comment by pea3nut** [comment]
fixed in 7.0.9
