### ISSUE TITLE
个人收藏页pxer报67994735:Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by banbiantan** [pea3nut/Pxer#51]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Google Chrome 正式版本 66.0.3359.139
- Pxer开发版 7.0.8

## Bug发生时的地址

https://www.pixiv.net/bookmark.php?id=17076518

## Bug发生时Pxer的状态

①在开启shadowsock（某一个翻墙软件）时
抛出一个warning：67994735:Cannot read property 'innerHTML' of null
失败列表显示：67994735 | 解析错误 | 再试一次，若问题依旧，请反馈给花生
                          68012805 | 解析错误 | 再试一次，若问题依旧，请反馈给花生
                          68012889 | 解析错误 | 再试一次，若问题依旧，请反馈给花生
等等
在点开count按钮时显示
共计0个作品，0个下载地址。
单张图片作品占 NaN%
多张图片作品占 NaN%

②关闭shadowsock即正常上网时
显示[ { "task": { "url": "https://www.pixiv.net/bookmark.php?id=17076518&p=5", "completed": false }, "url": "https://www.pixiv.net/bookmark.php?id=17076518&p=5" } ]

## Bug发生的具体情况

在发现p站又需要翻墙之后，开了shadowsock之后出现的问题①。抓取过程中一直很顺畅，最后完成时才报告bug。
问题②情况是，关闭shadowsock即正常上网时，无法打开p站，且利用翻墙打开页面后再次关闭翻墙软件进行抓取操作时，会在卡顿十几秒后显示第二个bug，其实就是pxer自己也被墙了。

**Comment by eternal-flame-AD** [comment]
新版本已正常。
如果是网络问题的话，duplicate of #13
