### ISSUE TITLE
作品页Pxer报 Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by balabala-233** [pea3nut/Pxer#52]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Google Chrome 版本 66.0.3359.139（正式版本） （64 位 / 版本 66.0.3359.170（正式版本） （64 位）（更新前后Bug情况相同）
- Pxer开发版 7.0.4 （可能是）

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?id=237196&type=all&p=5

## Bug发生时Pxer的状态

抓取结束，主面板显示“2992723:Cannot read property 'getAttribute' of null”，warn

## Bug发生的具体情况

当我用Pxer抓取上面地址的画师作品时，抓取结束后，状态是过滤选项和输出选项面板，右上角是黄色的warn，上方是“2992723:Cannot read property 'getAttribute' of null”。单击warn后表格如下

>图片ID | 失败原因 | 解决方案 | 全选 重试选中
>68664359 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
>55482471 | 解析错误 | 再试一次，若问题依旧，请反馈给花生 |  
>2992723 | 解析错误 | 再试一次，若问题依旧，请反馈给花生

单击全选，然后单击重试选中，Pxer回到抓取状态，右上角为蓝色run，显示程序状态、配置信息、当前页面信息、执行进度面板，任务未开始执行，配置信息未重置，主面板依旧显示相同报错。

再次点击run，抓取正常进行，结束后状态相同，右上角黄色warn，主面板错误信息相同

### 备注

- 这个作者不能关注

- 错误图片的网址
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68664359
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=55482471
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=2992723

**Comment by pea3nut** [comment]
fixed in 7.0.9
