### ISSUE TITLE
页面不能分析

### ISSUE THREAD

**Issue by cchenshizhi** [pea3nut/Pxer#53]
## 使用的系统、浏览器、Pxer版本

- Windows 7
- Firefox 延长支持版 47.4.0
- Pxer开发版 6.0.2

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?id=10009740

## Bug发生时Pxer的状态

“程序状态”窗口的“当前状态”一直卡在“抓取作品中”不动，并且主面板有提示`src.match(...) is null`。

## Bug发生的具体情况

当我用Pxer抓取上面地址的画师作品时，抓取到后面的时候偶尔会（30%几率左右的样子）在差10副作品左右时卡住不动，尝试过点击`Stop`按钮依旧无效。

**Comment by cchenshizhi** [comment]
页面都是分析失败

**Comment by pea3nut** [comment]
fixed in 7.0.9
