### ISSUE TITLE
抓取失败和没有下载地址

### ISSUE THREAD

**Issue by Kraken998** [pea3nut/Pxer#54]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Firefox 延长支持版 60.0.1
- Pxer开发版 7

## Bug发生时的地址
https://www.pixiv.net/bookmark.php

## Bug发生时Pxer的状态

“程序状态”窗口的“当前状态”一直卡在“抓取作品中”不动，并且主面板有提示[ { "task": { "url": "https://www.pixiv.net/bookmark.php?p=227", "completed": false }, "url": "https://www.pixiv.net/bookmark.php?p=227" } ]
2.抓取完成后跳转页面显示/** 这个页面是抓取到的下载地址，你可以将它们复制到第三方下载工具如QQ旋风中下载 */
/**
共计0个作品，0个下载地址。
单张图片作品占 NaN%
多张图片作品占 NaN%
*/

## Bug发生的具体情况
抓取是突然卡住不动 然后第二个就是抓取完了后没下载地址

**Comment by lancelucke** [comment]
同上，发生同样的问题


Bug发生时Pxer的状态
===================
抓取显示内容

/** 这个页面是抓取到的下载地址，你可以将它们复制到第三方下载工具如QQ旋风中下载 */
/**
共计0个作品，0个下载地址。
单张图片作品占 NaN%
多张图片作品占 NaN%
*/

===================
网页显示内容

图片ID | 失败原因 | 解决方案 | 全选 重试选中
-- | -- | -- | --
67946566 | 解析错误 | 再试一次，若问题依旧，请反馈给花生

===================

Bug发生的具体情况

抓取正常进行，读取数量，读条都正常
结束后弹出黄色warm

没抓取到任何内容

**Comment by huanghuaquan2018** [comment]
使用的系统、浏览器、Pxer版本

WIN7
UC 版本 6.2.39（正式版本）
Pxer开发版 7

Bug发生的具体情况

抓取正常进行，读取数量，读条都正常
结束后弹出黄色warm

没抓取到任何内容

**Comment by pea3nut** [comment]
fixed in 7.0.9
