### ISSUE TITLE
抓取失败，显示解析错误

### ISSUE THREAD

**Issue by cherrysakurali** [pea3nut/Pxer#57]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Chrome 67.0.3396.62 （64bit）
- Pxer开发版 7

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69136989

## Bug发生时Pxer的状态

显示已经完成，并弹出页面，但页面为空，状态显示解析错误（Cannot read property 'innerHTML' of null
）

## Bug发生的具体情况

正常抓取，根据网页源代码，怀疑是Pixiv修改了图片的显示方式，请求升级

**Comment by pea3nut** [comment]
fixed in 7.0.9
