### ISSUE TITLE
作品页Pxer报Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by balabala-233** [pea3nut/Pxer#58]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Google Chrome 版本 67.0.3396.99（正式版本） （64 位）
- Pxer开发版 7.0.8

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?id=3879871

## Bug发生时Pxer的状态

抓取完成，count “共计0个作品，0个下载地址。单张图片作品占 NaN% 多张图片作品占 NaN%”

## Bug发生的具体情况

抓取画师作品页，全部显示解析错误

**Comment by pea3nut** [comment]
fixed in 7.0.9

**Comment by balabala-233** [comment]
简直神速
