### ISSUE TITLE
抓取时弹窗但并无下载地址，报错Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by FBernkastel** [pea3nut/Pxer#59]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Chrome 版本 67.0.3396.99
- Pxer 7

## Bug发生时的地址

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=61269686

## Bug发生时Pxer的状态

弹出抓取窗口，但并无实际下载地址。

## Bug发生的具体情况

用Pxer抓取上面地址的画师作品时，弹出新窗口但并无地址。
原页面报错Cannot read property 'innerHTML' of null。

**Comment by pea3nut** [comment]
fixed in 7.0.9
