### ISSUE TITLE
在作者的收藏界面插件没有生效

### ISSUE THREAD

**Issue by k316447978** [pea3nut/Pxer#6]
如题，在P站收藏界面选项没有出现，用的是 Firefox 最新版，全部作者的收藏界面都没有出现插件选项，
开发版的插件，Pxer 没有任何提示。

这也是我第一次用，所以过滤选项中没有按收藏过滤的选项这一点不知道是不是 BUG。
（我个人没有收藏作品，个人收藏界面的情况不清楚）

**Comment by pea3nut** [comment]
请提供一下期望启动pxer的地址
pxer7.0没有“按收藏”过滤的功能

**Comment by k316447978** [comment]
比如http://www.pixiv.net/bookmark.php?id=8624721

**Comment by pea3nut** [comment]
貌似确实有问题，最近在答360的笔试，过段时间修复
