### ISSUE TITLE
抓取时弹窗但并无下载地址700多个对象一个都没有，报错Cannot read property 'innerHTML' of null 

### ISSUE THREAD

**Issue by primingeffect** [pea3nut/Pxer#60]
Windows 10
360极速浏览器版本号：9.5.0.134
内核版本：63.0.3239.132
Pxer 7

- Windows 7
- Firefox 延长支持版 47.4.0
- Pxer稳定版

## Bug发生时的地址

https://www.pixiv.net/search.php?s_mode=s_tag&word=%E3%82%BC%E3%83%AD%E3%81%8B%E3%82%89%E5%A7%8B%E3%82%81%E3%82%8B%E9%AD%94%E6%B3%95%E3%81%AE%E6%9B%B8

## Bug发生时Pxer的状态

最上端显示
41466599:Cannot read property 'innerHTML' of null
Warn99
其他正常 但是点开PRINT 里面下载地址个数为0
 ## Bug发生的具体情况
抓取完所有对象后最上端显示
41466599:Cannot read property 'innerHTML' of null
Warn99
其他正常 但是点开PRINT 里面下载地址个数为0

**Comment by primingeffect** [comment]
所以我要怎么做，看不懂代码。完全小白

**Comment by pea3nut** [comment]
@primingeffect 这个issue被commit自动关闭了，可以看到是上面“fix #60”这个commit关闭的。

简单来说，已经修复完成，将会在下个版本放出时生效
