### ISSUE TITLE
解析错误

### ISSUE THREAD

**Issue by FangAnn** [pea3nut/Pxer#71]
https://www.pixiv.net/member_illust.php?id=317803
pixiv 稳定版和开发版都失败win7 64位
        26550718:Unexpected token } in JSON at position 13840

解析错误 | 再试一次，若问题依旧，请反馈给花生
-- | --

**Comment by eternal-flame-AD** [comment]
git开发分支已正常。下次版本发布会修复服务器端文件

**Comment by eternal-flame-AD** [comment]
7.0.10已修复
