### ISSUE TITLE
大量解析错误

### ISSUE THREAD

**Issue by FangAnn** [pea3nut/Pxer#77]
- Windows 7
- Version: 7.0.9

https://www.pixiv.net/member_illust.php?id=189732
https://www.pixiv.net/member_illust.php?id=612602&type=all&p=2
https://www.pixiv.net/search.php?s_mode=s_tag&word=r-18%2010000users%E5%85%A5%E3%82%8A
https://www.pixiv.net/member_illust.php?id=6210796
https://www.pixiv.net/member_illust.php?id=787998
https://www.pixiv.net/member_illust.php?id=396769
https://www.pixiv.net/member_illust.php?id=2744600
https://www.pixiv.net/member_illust.php?id=5594793&type=all&p=3
https://www.pixiv.net/member_illust.php?id=714577
https://www.pixiv.net/member_illust.php?id=637016
https://www.pixiv.net/member_illust.php?id=10746425
https://www.pixiv.net/member_illust.php?id=17902
https://www.pixiv.net/member_illust.php?id=290366
https://www.pixiv.net/member_illust.php?id=420928
https://www.pixiv.net/member_illust.php?id=49693&type=all&p=5
https://www.pixiv.net/member_illust.php?id=17810
https://www.pixiv.net/member_illust.php?id=163536
https://www.pixiv.net/member_illust.php?id=9927548
https://www.pixiv.net/member_illust.php?id=1655331
https://www.pixiv.net/member_illust.php?id=3999381
https://www.pixiv.net/member_illust.php?id=144415
https://www.pixiv.net/member_illust.php?id=3624793
https://www.pixiv.net/member_illust.php?id=245600
https://www.pixiv.net/member_illust.php?id=777703
https://www.pixiv.net/member_illust.php?id=3004637
https://www.pixiv.net/member_illust.php?id=1204169
都解析错误应该不是我的IP DNS的问题可正常访问就是解析错误w(ﾟДﾟ)w

**Comment by eternal-flame-AD** [comment]
昨天git分支修了一个很大的bug，应该是这个问题，下个release会合并到服务器上

我今天晚些时候测试你给的地址之后给你明确答复

**Comment by eternal-flame-AD** [comment]
已测试（并没有爬完全部页面，每个爬了一些）
此issue提到的问题已在 #67 #68 中修复，下个release会生效。

**Comment by eternal-flame-AD** [comment]
7.0.10版本已修复
