### ISSUE TITLE
无法顺利更新至7.0.10

### ISSUE THREAD

**Issue by sivor0811** [pea3nut/Pxer#80]
## 使用的系统、浏览器、Pxer版本

- Windows 7
- chrome 67.0.3396.99
- Pxer开发版 7.0.9

## Bug发生时的地址

本机

## Bug发生时Pxer的状态

7.0.9发生大量解析错误

## Bug发生的具体情况
我选择从Tampermonkey删除Pxer开发版后，再透过网页重新安装，发现版本还是维持7.0.9

**Comment by eternal-flame-AD** [comment]
服务器端文件还没更新

**Comment by pea3nut** [comment]
7.0.10流产了，刚刚更新了7.0.11
