### ISSUE TITLE
建议：本地存储 配置信息 （抓取历史？）

### ISSUE THREAD

**Issue by balabala-233** [pea3nut/Pxer#87]
能保留设置吗，每次更改设置好累

**Comment by eternal-flame-AD** [comment]
你觉得有哪些设置要保存呢？
点赞数，页数还是？个人感觉这些参数不是很稳定的
输出参数可以考虑

**Comment by eternal-flame-AD** [comment]
我有个想法是保存上次抓取作者/收藏的时间，下次自动从那个继续这样比较人性化

**Comment by balabala-233** [comment]
作品页的“配置信息”

在 2018-07-11 23:12:57，"_eternal_flame" <notifications@github.com> 写道：


你觉得有哪些设置要保存呢？
点赞数，页数还是？个人感觉这些参数不是很稳定的
输出参数可以考虑

**Comment by eternal-flame-AD** [comment]
可以考虑的~ @pea3nut 你怎么看？

**Comment by balabala-233** [comment]
嗯，那样会方便许多

在 2018-07-11 23:15:40，"_eternal_flame" <notifications@github.com> 写道：


我有个想法是保存上次抓取作者/收藏的时间，下次自动从那个继续这样比较人性化

**Comment by balabala-233** [comment]
谢谢啦

在 2018-07-11 23:17:30，"_eternal_flame" <notifications@github.com> 写道：


可以考虑的~ @pea3nut 你怎么看？

**Comment by pea3nut** [comment]
我没理解“作品页的配置信息”是什么意思？可以截图说明下吗？ @balabala-233

**Comment by balabala-233** [comment]
![2018-07-12 -](https://user-images.githubusercontent.com/33023501/42609151-afc864a0-85bd-11e8-8fb3-075baafccf9d.png)
这个

**Comment by pea3nut** [comment]
那我认为这个明显是弊大于利的

**Comment by balabala-233** [comment]
好吧
