### ISSUE TITLE
Pxer7 bug：扒不出链接，时间是2017.03.30中午发现

### ISSUE THREAD

**Issue by krnagi** [pea3nut/Pxer#9]
## 使用的系统、浏览器、Pxer版本

- Windows 10
- Firefox ESR 52.0.1 (32 位)
- Pxer开发版

## Bug发生时的地址
每个画师……
当前试验的画师是http://www.pixiv.net/member_illust.php?id=50117

## Bug发生时Pxer的状态

“程序状态”窗口的“当前状态”一直卡在“抓取作品中”不动，并且主面板有提示`962819:src.match(...) is null`。

## Bug发生的具体情况
点count的时候，显示
共计0个作品，0个下载地址。
单张图片作品占 NaN%
多张图片作品占 NaN%
点print也确实一张链接都没有……
重新扒取也是这样
换成稳定版也是

**Comment by pea3nut** [comment]
这么严重？每个画师？看来是P站有所动作啊.......

**Comment by krnagi** [comment]
嗯……一开始我还不信邪……试了别的画师，，，然后一位是公司的网的原因，回家了又试过，最后一位账号原因……找朋友也试了下，果然是p站搞事吗……
